version: "3"

services:
  olympics-visualizer:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: olympics-visualizer
    image: olympics-visualizer:${IMAGE_TAG}
    ports:
      - "8088:8088"
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/amd64
    volumes:
      - superset_db:/opt/superset/db

volumes:
  superset_db:
